### ISSUE TITLE
長音で終わる語の次の語のルールが不明瞭

### ISSUE THREAD

**Issue by piroor** [laco0416/shiritori#13]
「レッキングクルー」に続く言葉としてどのような語が許容されるのかが不明です。
https://ja.wikipedia.org/wiki/%E3%81%97%E3%82%8A%E3%81%A8%E3%82%8A では以下のようなルールの例が紹介されています。
- 厳密に「ルー」で継続（例：レッキングクルー→ルール）
- 長音を母音に変換して継続（例：レッキングクルー（レッキングクルウ）→うさぎ）
- 長音を無視して継続（例：レッキングクルー→ルンバ）

どのようなルールとなるのか、CONTRIBUTING.mdに明記していただく事は可能でしょうか？

**Comment by lacolaco** [comment]
おっしゃるとおりです。やります。

今回の場合ですと、「ルー」から始まる言葉に限定することとします。

**Comment by lacolaco** [comment]
done
