### ISSUE TITLE
「レッキングクルー」の棄却と代替単語の募集

### ISSUE THREAD

**Issue by lacolaco** [laco0416/shiritori#21]
「レッキングクルー」は特定の商品の名称であるため、棄却されるのが望ましい。

次の単語は「ルーマニア」であるので、「レ」から始まり、「ルー」、あるいは「ル」で終わる単語を特別に募集する

**Comment by kiris** [comment]
refs: https://github.com/laco0416/shiritori/pull/15#issuecomment-230695084

**Comment by suzutan** [comment]
ル　で終わる単語であれば、レベル、レール、レーベル　などでしょうか。

**Comment by lacolaco** [comment]
`レール` を採用することとします。

**Comment by lacolaco** [comment]
Thanks @suzutan !
